//
//  Copyright 2021  Alexandra Hermann – Beratung, Software, Design
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ahbsd.lib.Nutrients.Nutrient;
//
//    var nutrients = Nutrients.FromJson(jsonString);
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ahbsd.lib.Nutrients.Nutrient
{
    /// <summary>
    /// A Class for Nutrients translation.
    /// </summary>
    public partial class Nutrients : INutrients
    {
        /// <summary>
        /// Gets or sets the nutrient translation.
        /// </summary>
        /// <value>The nutrient translation.</value>
        [JsonProperty("NutrientTranslation")]
        public NutrientTranslation NutrientTranslation { get; set; }
    }

    /// <summary>
    /// A Class for translating nutrients.
    /// </summary>
    public partial class NutrientTranslation : INutrientTranslation
    {
        #region implementation of INutrientTranslation
        /// <summary>
        /// Gets or sets the translation of Biotin.
        /// </summary>
        /// <value>The translation of Biotin.</value>
        [JsonProperty("Biotin")]
        public string Biotin { get; set; }

        /// <summary>
        /// Gets or sets the translation of Caffeine.
        /// </summary>
        /// <value>The translation of Caffeine.</value>
        [JsonProperty("Caffeine")]
        public string Caffeine { get; set; }

        /// <summary>
        /// Gets or sets the translation of Calcium.
        /// </summary>
        /// <value>The translation of Calcium.</value>
        [JsonProperty("Calcium")]
        public string Calcium { get; set; }

        /// <summary>
        /// Gets or sets the translation of Carbohydrates.
        /// </summary>
        /// <value>The translation of Carbohydrates.</value>
        [JsonProperty("Carbohydrates")]
        public string Carbohydrates { get; set; }

        /// <summary>
        /// Gets or sets the translation of Chloride.
        /// </summary>
        /// <value>The translation of Chloride.</value>
        [JsonProperty("Chloride")]
        public string Chloride { get; set; }

        /// <summary>
        /// Gets or sets the translation of Cholesterol.
        /// </summary>
        /// <value>The translation of Cholesterol.</value>
        [JsonProperty("Cholesterol")]
        public string Cholesterol { get; set; }

        /// <summary>
        /// Gets or sets the translation of Chromium.
        /// </summary>
        /// <value>The translation of Chromium.</value>
        [JsonProperty("Chromium")]
        public string Chromium { get; set; }

        /// <summary>
        /// Gets or sets the translation of Copper.
        /// </summary>
        /// <value>The translation of Copper.</value>
        [JsonProperty("Copper")]
        public string Copper { get; set; }

        /// <summary>
        /// Gets or sets the translation of FatMonosaturated.
        /// </summary>
        /// <value>The translation of FatMonosaturated.</value>
        [JsonProperty("FatMonosaturated")]
        public string FatMonosaturated { get; set; }

        /// <summary>
        /// Gets or sets the translation of FatPolysaturated.
        /// </summary>
        /// <value>The translation of FatPolysaturated.</value>
        [JsonProperty("FatPolysaturated")]
        public string FatPolysaturated { get; set; }

        /// <summary>
        /// Gets or sets the translation of FatSaturated.
        /// </summary>
        /// <value>The translation of FatSaturated.</value>
        [JsonProperty("FatSaturated")]
        public string FatSaturated { get; set; }

        /// <summary>
        /// Gets or sets the translation of FatTotal.
        /// </summary>
        /// <value>The translation of FatTotal.</value>
        [JsonProperty("FatTotal")]
        public string FatTotal { get; set; }

        /// <summary>
        /// Gets or sets the translation of Fiber.
        /// </summary>
        /// <value>The translation of Fiber.</value>
        [JsonProperty("Fiber")]
        public string Fiber { get; set; }

        /// <summary>
        /// Gets or sets the translation of Folate.
        /// </summary>
        /// <value>The translation of Folate.</value>
        [JsonProperty("Folate")]
        public string Folate { get; set; }

        /// <summary>
        /// Gets or sets the translation of Iodine.
        /// </summary>
        /// <value>The translation of Iodine.</value>
        [JsonProperty("Iodine")]
        public string Iodine { get; set; }

        /// <summary>
        /// Gets or sets the translation of Iron.
        /// </summary>
        /// <value>The translation of Iron.</value>
        [JsonProperty("Iron")]
        public string Iron { get; set; }

        /// <summary>
        /// Gets or sets the translation of Magnesium.
        /// </summary>
        /// <value>The translation of Magnesium.</value>
        [JsonProperty("Magnesium")]
        public string Magnesium { get; set; }

        /// <summary>
        /// Gets or sets the translation of Manganese.
        /// </summary>
        /// <value>The translation of Manganese.</value>
        [JsonProperty("Manganese")]
        public string Manganese { get; set; }

        /// <summary>
        /// Gets or sets the translation of Molybdenum.
        /// </summary>
        /// <value>The translation of Molybdenum.</value>
        [JsonProperty("Molybdenum")]
        public string Molybdenum { get; set; }

        /// <summary>
        /// Gets or sets the translation of Niacin.
        /// </summary>
        /// <value>The translation of Niacin.</value>
        [JsonProperty("Niacin")]
        public string Niacin { get; set; }

        /// <summary>
        /// Gets or sets the translation of PantotenicAcid.
        /// </summary>
        /// <value>The translation of PantotenicAcid.</value>
        [JsonProperty("PantotenicAcid")]
        public string PantotenicAcid { get; set; }

        /// <summary>
        /// Gets or sets the translation of Phosphorus.
        /// </summary>
        /// <value>The translation of Phosphorus.</value>
        [JsonProperty("Phosphorus")]
        public string Phosphorus { get; set; }

        /// <summary>
        /// Gets or sets the translation of Potassium.
        /// </summary>
        /// <value>The translation of Potassium.</value>
        [JsonProperty("Potassium")]
        public string Potassium { get; set; }

        /// <summary>
        /// Gets or sets the translation of Protein.
        /// </summary>
        /// <value>The translation of Protein.</value>
        [JsonProperty("Protein")]
        public string Protein { get; set; }

        /// <summary>
        /// Gets or sets the translation of Riboflavin.
        /// </summary>
        /// <value>The translation of Riboflavin.</value>
        [JsonProperty("Riboflavin")]
        public string Riboflavin { get; set; }

        /// <summary>
        /// Gets or sets the translation of Selenium.
        /// </summary>
        /// <value>The translation of Selenium.</value>
        [JsonProperty("Selenium")]
        public string Selenium { get; set; }

        /// <summary>
        /// Gets or sets the translation of Sodium.
        /// </summary>
        /// <value>The translation of Sodium.</value>
        [JsonProperty("Sodium")]
        public string Sodium { get; set; }

        /// <summary>
        /// Gets or sets the translation of Sugar.
        /// </summary>
        /// <value>The translation of Sugar.</value>
        [JsonProperty("Sugar")]
        public string Sugar { get; set; }

        /// <summary>
        /// Gets or sets the translation of Thiamin.
        /// </summary>
        /// <value>The translation of Thiamin.</value>
        [JsonProperty("Thiamin")]
        public string Thiamin { get; set; }

        /// <summary>
        /// Gets or sets the translation of VitaminA.
        /// </summary>
        /// <value>The translation of VitaminA.</value>
        [JsonProperty("VitaminA")]
        public string VitaminA { get; set; }

        /// <summary>
        /// Gets or sets the translation of VitaminB12.
        /// </summary>
        /// <value>The translation of VitaminB12.</value>
        [JsonProperty("VitaminB12")]
        public string VitaminB12 { get; set; }

        /// <summary>
        /// Gets or sets the translation of VitaminB6.
        /// </summary>
        /// <value>The translation of VitaminB6.</value>
        [JsonProperty("VitaminB6")]
        public string VitaminB6 { get; set; }

        /// <summary>
        /// Gets or sets the translation of VitaminC.
        /// </summary>
        /// <value>The translation of VitaminC.</value>
        [JsonProperty("VitaminC")]
        public string VitaminC { get; set; }

        /// <summary>
        /// Gets or sets the translation of VitaminD.
        /// </summary>
        /// <value>The translation of VitaminD.</value>
        [JsonProperty("VitaminD")]
        public string VitaminD { get; set; }

        /// <summary>
        /// Gets or sets the translation of VitaminE.
        /// </summary>
        /// <value>The translation of VitaminE.</value>
        [JsonProperty("VitaminE")]
        public string VitaminE { get; set; }

        /// <summary>
        /// Gets or sets the translation of VitaminK.
        /// </summary>
        /// <value>The translation of VitaminK.</value>
        [JsonProperty("VitaminK")]
        public string VitaminK { get; set; }

        /// <summary>
        /// Gets or sets the translation of Water.
        /// </summary>
        /// <value>The translation of Water.</value>
        [JsonProperty("Water")]
        public string Water { get; set; }

        /// <summary>
        /// Gets or sets the translation of Zinc.
        /// </summary>
        /// <value>The translation of Zinc.</value>
        [JsonProperty("Zinc")]
        public string Zinc { get; set; }

        /// <summary>
        /// Gets or sets the translation of Alcohol.
        /// </summary>
        /// <value>The translation of Alcohol.</value>
        [JsonProperty("Alcohol")]
        public string Alcohol { get; set; }

        /// <summary>
        /// Gets or sets the translation of Energy.
        /// </summary>
        /// <value>The translation of Energy.</value>
        [JsonProperty("Energy")]
        public string Energy { get; set; }
        #endregion
    }

    /// <summary>
    /// A Class for Nutrients.
    /// </summary>
    public partial class Nutrients
    {
        /// <summary>
        /// Static function to get the translation from a json string.
        /// </summary>
        /// <param name="json">The json string.</param>
        /// <returns>A nutrients object with the translated nutrients.</returns>
        public static Nutrients FromJson(string json) => JsonConvert.DeserializeObject<Nutrients>(json, ahbsd.lib.Nutrients.Nutrient.FoodNutrientsConverter.Settings);
    }

    /// <summary>
    /// Serialization-Class.
    /// </summary>
    public static class NutrientsSerialize
    {
        /// <summary>
        /// Static function to set the translation json string from a nutrients object.
        /// </summary>
        /// <param name="self">The <see cref="Nutrients"/> object.</param>
        /// <returns>The json string.</returns>
        public static string ToJson(this Nutrients self) => JsonConvert.SerializeObject(self, ahbsd.lib.Nutrients.Nutrient.FoodNutrientsConverter.Settings);
    }

    /// <summary>
    /// A converter class.
    /// </summary>
    internal static class FoodNutrientsConverter
    {
        /// <summary>
        /// Static Settings.
        /// </summary>
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

