//
//  Copyright 2021  Alexandra Hermann – Beratung, Software, Design
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ahbsd.lib.Nutrients.Nutrient;
//
//    var foodNutrientsSchema = FoodNutrientsSchema.FromJson(jsonString);
using Newtonsoft.Json;

namespace ahbsd.lib.Nutrients.Nutrient.Schema
{
    /// <summary>
    /// An interface for a FoodNutrients Schema.
    /// </summary>
    public interface IFoodNutrientsSchema
    {
        /// <summary>
        /// The default amount in gram or mililiter the food nutrients are measured for. Usually 100
        /// gram or 100 mililiter.
        /// </summary>
        [JsonProperty("DefaultAmount")]
        double DefaultAmount { get; set; }
        /// <summary>
        /// The measurement of the default amount.
        /// </summary>
        [JsonProperty("DefaultMeasurement")]
        Measurement DefaultMeasurement { get; set; }
        /// <summary>
        /// The first date, when this version was marked.
        /// </summary>
        [JsonProperty("FirstDate")]
        string FirstDate { get; set; }
        /// <summary>
        /// The name of the food, for which the nutrients are saved.
        /// </summary>
        [JsonProperty("Name")]
        string Name { get; set; }
        /// <summary>
        /// The nutrients in the food. If not available: null
        /// </summary>
        [JsonProperty("NutrientValues")]
        NutrientsInTheFood NutrientValues { get; set; }
        /// <summary>
        /// Nutrients of a food change from time to time. So versioning is quite useful.
        /// </summary>
        [JsonProperty("Version")]
        double Version { get; set; }
    }
}