//
//  Copyright 2021  Alexandra Hermann – Beratung, Software, Design
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ahbsd.lib.Nutrients.Nutrient;
//
//    var foodNutrientsSchema = FoodNutrientsSchema.FromJson(jsonString);
namespace ahbsd.lib.Nutrients.Nutrient.Schema
{
    public interface INutrientsInTheFood
    {
        double? Alcohol { get; set; }
        double? Biotin { get; set; }
        double? Caffeine { get; set; }
        double? Calcium { get; set; }
        double? Carbohydrates { get; set; }
        double? Chloride { get; set; }
        double? Cholesterol { get; set; }
        double? Chromium { get; set; }
        double? Copper { get; set; }
        double Energy { get; set; }
        double? FatMonosaturated { get; set; }
        double? FatPolysaturated { get; set; }
        double? FatSaturated { get; set; }
        double? Fiber { get; set; }
        double? Folate { get; set; }
        double? Iodine { get; set; }
        double? Iron { get; set; }
        double? Magnesium { get; set; }
        double? Manganese { get; set; }
        double? Molybdenum { get; set; }
        double? Niacin { get; set; }
        double? PantotenicAcid { get; set; }
        double? Phosphorus { get; set; }
        double? Potassium { get; set; }
        double? Protein { get; set; }
        double? Riboflavin { get; set; }
        double? Selenium { get; set; }
        double? Sodium { get; set; }
        double? Sugar { get; set; }
        double? Thiamin { get; set; }
        double? VitaminA { get; set; }
        double? VitaminB12 { get; set; }
        double? VitaminB6 { get; set; }
        double? VitaminC { get; set; }
        double? VitaminD { get; set; }
        double? VitaminE { get; set; }
        double? VitaminK { get; set; }
        double? Water { get; set; }
        double? Zinc { get; set; }
    }
}